### ISSUE TITLE
unresolved external symbol ofxGLFWJoystick::isJoystickAvailable(int)

### ISSUE THREAD

**Issue by Scylardor** [armadillu/ofxGLFWJoystick#4]
Hi,
I am using ofxGLFWJoystick on Windows with Visual Studio (MSVC version 17.11.2) and it works great, except when I use the Release configuration.

In Debug everything compiles fine.
In Release, an error pops:
error LNK2001: unresolved external symbol "public: bool __cdecl ofxGLFWJoystick::isJoystickAvailable(int)" (?isJoystickAvailable@ofxGLFWJoystick@@QEAA_NH@Z)

I think the error is that `isJoystickAvailable` is declared inline:
```inline bool isJoystickAvailable(int joyID);```
( https://github.com/armadillu/ofxGLFWJoystick/blob/8769513aa24b09fb8e2549d820a4506239b708aa/src/ofxGLFWJoystick.h#L39 )

It is invalid to declare inline a function that's defined in a separate translation unit (isJoystickAvailable is not visible to user files). It is possible the compiler ignores the inline keyword in Debug, hence why it would be working.

I would suggest to simply remove the inline keyword from the header file, or put the implementation in the header (so the function can be properly inlined), whatever makes the most sense to you.

**Comment by armadillu** [comment]
Yes, no idea why I defined as inline. Thanks!
